### ISSUE TITLE
 Couldn't load tag forge:ores as it is missing following references

### ISSUE THREAD

**Issue by WildPowerHammer** [VeroxUniverse/EpicKightsnMages-NeoForge#2]
I have a some issues with that mod in modpack:
![изображение](https://github.com/VeroxUniverse/EpicKightsnMages-NeoForge/assets/136165053/5757e618-3498-4b35-9609-28b1aa3307b5)

First issue i found is prospecting hammer from silent gear stop working because of that.

**Comment by VeroxUniverse** [comment]
I fixed it

**Comment by WildPowerHammer** [comment]
You are best! Thanks you
