### ISSUE TITLE
Error with armor render

### ISSUE THREAD

**Issue by Valdifer** [VeroxUniverse/EpicKightsnMages-NeoForge#3]
![image](https://github.com/VeroxUniverse/EpicKightsnMages-NeoForge/assets/37176834/c16fd2c0-940a-4391-b673-19f60d7cfd72)

When someone equips the armor, the render its binded to that client, that means for example, if i craft the armor, and i equip the helmet and i equip the chest but if other guy like the picture create the leggings and boots and equip them, the first one which equips the armor its only the person that can see that piece of armor, all the other guys can't see the equipped armor in their clients

**Comment by VeroxUniverse** [comment]
It is not compatible with epic fight
