### ISSUE TITLE
Allthemodium sets missing features

### ISSUE THREAD

**Issue by RunicFurry** [VeroxUniverse/EpicKightsnMages-NeoForge#4]
Crafted the allthemodium variant of battlemage robes and it seems they don't have all the features of allthemodium armor sets. These being:
- Not being able to drown
- Not taking kinetic damage
- Not taking fire damage
- Not taking fall damage
I'd really like this to be adressed as without these features there is no reason to use these armor sets if one decides to add this mod to ATM9 other than for their look.

**Comment by VeroxUniverse** [comment]
I will remove them for the update. 
I will seperate all compat armor into addons.

**Comment by VeroxUniverse** [comment]
what means that they will get all features with the addon

**Comment by RunicFurry** [comment]
Cool, thanks for adressing it.
